package io.github.project_minigraf.minigraf

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

// MiniGrafDb and MiniGrafException are generated by uniffi-bindgen into
// src/main/kotlin/uniffi/minigraf_ffi/. They are imported transitively.
// The exact generated package path is uniffi.minigraf_ffi — adjust if different.
import uniffi.minigraf_ffi.MiniGrafDb
import uniffi.minigraf_ffi.MiniGrafException

private val mapper = jacksonObjectMapper()

class BasicTest {

    @Test
    fun testOpenInMemory() {
        val db = MiniGrafDb.openInMemory()
        assertNotNull(db)
    }

    @Test
    fun testTransactAndQuery() {
        val db = MiniGrafDb.openInMemory()
        val txJson = db.execute("""(transact [[:alice :name "Alice"]])""")
        val tx: Map<String, Any> = mapper.readValue(txJson)
        assertTrue(tx.containsKey("transacted"), "expected transacted key")

        val queryJson = db.execute("(query [:find ?n :where [?e :name ?n]])")
        val qr: Map<String, Any> = mapper.readValue(queryJson)
        @Suppress("UNCHECKED_CAST")
        val results = qr["results"] as List<List<Any>>
        assertEquals("Alice", results[0][0])
    }

    @Test
    fun testInvalidDatalogThrows() {
        val db = MiniGrafDb.openInMemory()
        assertThrows<MiniGrafException> {
            db.execute("not valid datalog !!!")
        }
    }

    @Test
    fun testFileBacked() {
        val tmp = File.createTempFile("minigraf_jvm_test", ".graph")
        tmp.deleteOnExit()
        val walFile = File(tmp.absolutePath + ".wal")
        walFile.deleteOnExit()

        val db = MiniGrafDb.open(tmp.absolutePath)
        db.execute("""(transact [[:bob :name "Bob"]])""")
        db.checkpoint()
        db.destroy()  // UniFFI frees the Arc reference

        val db2 = MiniGrafDb.open(tmp.absolutePath)
        val queryJson = db2.execute("(query [:find ?n :where [?e :name ?n]])")
        val qr: Map<String, Any> = mapper.readValue(queryJson)
        @Suppress("UNCHECKED_CAST")
        val results = qr["results"] as List<List<Any>>
        assertEquals("Bob", results[0][0])
    }
}
